version: "3.8"
services:
  postgres:
    container_name: postgres
    image: docker.io/postgres:11.12-alpine
    environment:
      POSTGRES_USER: touch
      POSTGRES_PASSWORD: touch
      POSTGRES_DB: touch
    ports:
      - 5432:5432

  service.rpc.users:
    container_name: service.rpc.users
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        SERVICE: service.rpc.users
    depends_on:
      postgres:
        condition: service_started
    ports:
      - 8080:8080

  service.rpc.assets:
    container_name: service.rpc.assets
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        SERVICE: service.rpc.assets
    depends_on:
      postgres:
        condition: service_started
      service.rpc.orders:
        condition: service_started
    ports:
      - 8081:8080

  service.rpc.orders:
    container_name: service.rpc.orders
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        SERVICE: service.rpc.orders
    depends_on:
      postgres:
        condition: service_started
    ports:
      - 8082:8080
